import React, { useState } from 'react'
import {Card, Loader, FormField} from '../components'
function Home() {
  const [loading, setLoading] = useState(true)
  return (
    <section className='max-w-7xl mx-auto'>
      <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
      <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>

      <div className='mt-16'>
        <FormField/>
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ): (
          <></>
        )}
      </div>
    </section>
  )
}

export default Home